# Started only for the WORKER_PROXY spooling retrieval mode, in which the
# coordinator redirects segment downloads to a worker.
coordinator=false
http-server.http.port=8080
discovery.uri=http://trino-go-client-tests:8080
internal-communication.shared-secret=gotrino

protocol.spooling.enabled=true
protocol.spooling.shared-secret-key=jxTKysfCBuMZtFqUf8UJDQ1w9ez8rynEJsJqgJf66u0=
# workers serve segment downloads only in this mode
protocol.spooling.retrieval-mode=worker_proxy
protocol.spooling.inlining.max-rows=1000
protocol.spooling.inlining.max-size=128kB
protocol.spooling.initial-segment-size=128kB
protocol.spooling.max-segment-size=256kB
