name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['>=1.27', '1.25.5']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v -race -timeout 30s ./...
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['>=1.27', '1.25.5']
        trino: ['latest', '372']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test -C integration -v -race -timeout 2m ./... -trino_image_tag=${{ matrix.trino }}
